version: '3'

services:
  db:
    image: postgres
  server:
    build: .
    command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - db
