# Generated by Django 2.0.3 on 2018-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('week', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
