# Generated by Django 2.0.3 on 2018-04-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20180419_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
