# Generated by Django 2.0.3 on 2018-04-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20180419_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('end_date', models.DateField()),
                ('value', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('previous_week', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_week', to='chart.Week')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
    ]
