# Generated by Django 2.0.3 on 2018-04-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20180421_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='week',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chart.Commodity'),
        ),
    ]
