# Generated by Django 2.0.3 on 2018-04-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20180422_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
